cache:
  paths:
    - vendor/

stages:
  - prepare
  - build
  - deploy

prepare:
  image: alpine/git
  stage: prepare
  script:
    # checkout submodule
    - git submodule init && git submodule update
  cache:
    paths:
      - ./jikan-rest

build:
  image: composer
  stage: build
  script:
    - composer install --optimize-autoloader --quiet
  cache:
    paths:
      - ./jikan-rest

deploy docker image:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

deploy tagged docker image:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
