stages:
  - build
  - deploy

variables:
  GIT_SUBMODULE_STRATEGY: recursive

cache:
  paths:
    - ./jikan-rest/vendor

build:
  image: composer
  stage: build
  script:
    - cd ./jikan-rest
    - composer install --optimize-autoloader --quiet

deploy docker image:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - master

deploy tagged docker image:
  stage: deploy
  image: docker:git
  services:
    - docker:dind
  script:
    - docker login -u "gitlab-ci-token" -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags
