version: '3'
services:
  web:
    image: nginx:alpine
    container_name: jikan_rest_web
    restart: always
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./jikan-rest:/app
    ports:
      - ${PORT}:80
    links:
      - php
  composer:
    image: composer:latest
    restart: 'no'
    command: install
    volumes:
      - ./jikan-rest:/app
  php:
    image: php:7-fpm-alpine
    container_name: jikan_rest_app
    restart: always
    volumes:
      - ./jikan-rest:/app
    env_file:
      - ./jikan.env
  redis:
    image: redis:5-alpine
    container_name: jikan_rest_redis
    restart: always
    volumes:
      - ./docker/data/redis:/data
  mysql:
    image: mysql:5.7
    container_name: jikan_rest_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=homestead
    volumes:
      - ./docker/data/db/mysql:/var/lib/mysql
