version: '3'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: jikan-rest-app:latest
    container_name: jikan_rest_app
    restart: always
    ports:
      - ${PORT}:80
  redis:
    image: redis:5-alpine
    container_name: jikan_rest_redis
    restart: always
    volumes:
      - "./docker/data/redis:/data"
  mysql:
    image: mysql:5.7
    container_name: jikan_rest_mysql
    restart: always
    environment:
      - MYSQL_DATABASE=homestead
      - MYSQL_ROOT_PASSWORD=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=homestead
    volumes:
      - "./docker/data/db/mysql:/var/lib/mysql"
