version: '3'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./jikan-rest:/app
    ports:
      - ${PORT}:80
    depends_on:
      - php
  composer:
    image: composer
    restart: 'no'
    command: 'install --no-dev'
    volumes:
      - ./jikan-rest:/app
  php:
    image: php:7-fpm-alpine
    restart: unless-stopped
    volumes:
      - ./jikan-rest:/app
    env_file:
      - ./jikan.env
    depends_on:
      - composer
  redis:
    image: redis:5-alpine
    restart: unless-stopped
    volumes:
      - ./docker/data/redis:/data
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=homestead
      - MYSQL_USER=homestead
      - MYSQL_PASSWORD=homestead
    volumes:
      - ./docker/data/db/mysql:/var/lib/mysql
