version: '3'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./site.conf:/etc/nginx/conf.d/default.conf
      - ./jikan-rest:/app
    ports:
      - ${PORT}:80
    depends_on:
      - php
  php:
    build: .
    restart: unless-stopped
  redis:
    image: redis:5-alpine
    restart: unless-stopped
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=jikan
      - MYSQL_USER=jikan
      - MYSQL_PASSWORD=jikan
