FROM php:7-fpm-alpine

ENV APP_ENV=production
ENV APP_DEBUG=false
ENV APP_KEY=jikan-rest
ENV APP_TIMEZONE=UTC

ENV DB_CONNECTION=mysql
ENV DB_HOST=mysql
ENV DB_PORT=3306
ENV DB_DATABASE=jikan
ENV DB_USERNAME=jikan
ENV DB_PASSWORD=jikan

ENV CACHE_DRIVER=redis
ENV QUEUE_DRIVER=redis

ENV CACHE_METHOD=legacy
ENV CACHE_DEFAULT_EXPIRE=86400
ENV CACHE_META_EXPIRE=300
ENV CACHE_USER_EXPIRE=300
ENV CACHE_404_EXPIRE=604800
ENV CACHE_SEARCH_EXPIRE=432000

ENV QUEUE_DELAY_PER_JOB=5

ENV THROTTLE=false
ENV THROTTLE_DECAY_MINUTES=1
ENV THROTTLE_MAX_PER_DECAY_MINUTES=30
ENV THROTTLE_MAX_PER_SECOND=2

ENV SLAVE_INSTANCE=false
ENV SLAVE_KEY=null
ENV SLAVE_CLIENT_IP_HEADER=X-Real-IP
ENV SLAVE_KEY_HEADER=X-Master

ENV REDIS_HOST=redis
ENV REDIS_PASSWORD=null
ENV REDIS_PORT=6379

ENV GITHUB_REPORTING=false
ENV GITHUB_REST=jikan-me/jikan-rest
ENV GITHUB_API=jikan-me/jika

WORKDIR /app

COPY ./jikan-rest /app
