version: '3'
services:
  web:
    image: nginx:alpine
    restart: unless-stopped
    volumes:
      - ./conf:/etc/nginx/conf.d
      - ./jikan-rest:/app
    ports:
      - ${PORT}:80
    depends_on:
      - php
  composer:
    image: composer
    restart: 'no'
    command: 'install --no-dev --optimize-autoloader --quiet'
    volumes:
      - ./jikan-rest:/app
  php:
    build: .
    restart: unless-stopped
  redis:
    image: redis:5-alpine
    restart: unless-stopped
  mysql:
    image: mysql:5.7
    restart: unless-stopped
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=1
      - MYSQL_DATABASE=jikan
      - MYSQL_USER=jikan
      - MYSQL_PASSWORD=jikan
